import 'package:flutter/widgets.dart';
import 'package:flutter_boilerplate/core/l10n/gen/app_localizations.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

export 'package:flutter_boilerplate/core/l10n/gen/app_localizations.dart';

/// Localization wiring for `MaterialApp.router`.
///
/// NOTE: `AppLocalizations` is generated by `flutter gen-l10n` (run on build or
/// via `flutter pub get`). Do not edit the generated `gen/` folder by hand.
abstract final class L10n {
  static const List<Locale> supportedLocales =
      AppLocalizations.supportedLocales;

  static const Iterable<LocalizationsDelegate<dynamic>> delegates = [
    AppLocalizations.delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];
}

/// Convenience accessor: `context.l10n.signInTitle`.
extension L10nX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
